version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/admin-web"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    groups:
      admin-web:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/backend"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:20"
      timezone: "UTC"
    groups:
      backend-python:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github_actions"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:40"
      timezone: "UTC"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/backend"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"

  - package-ecosystem: "docker"
    directory: "/admin-web"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:20"
      timezone: "UTC"

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:40"
      timezone: "UTC"
