"""Persistence contract for private remote-follow discovery state."""

from datetime import datetime, timezone
from importlib.util import module_from_spec, spec_from_file_location
import os
from pathlib import Path
import subprocess
import sys
from urllib.parse import urlparse, urlunparse
from uuid import uuid4

import pytest
from pydantic import ValidationError
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.exc import IntegrityError


@pytest.mark.integration
def test_f4_backfills_every_predecessor_valid_subscription_schedule(
    test_database_url,
    test_db_base_url,
):
    """Tightening membership checks must not reject rows accepted at the b3 boundary."""
    import asyncio
    import asyncpg

    database_name = f"autogallery_remote_backfill_{uuid4().hex[:12]}"
    database_url = urlunparse(
        urlparse(test_database_url)._replace(path=f"/{database_name}")
    )
    asyncpg_url = database_url.replace("postgresql+asyncpg://", "postgresql://")
    backend_dir = Path(__file__).resolve().parents[1]

    async def create_database_and_predecessor_schema() -> None:
        admin = await asyncpg.connect(test_db_base_url, timeout=3)
        try:
            await admin.execute(f'CREATE DATABASE "{database_name}"')
        finally:
            await admin.close()

        connection = await asyncpg.connect(asyncpg_url, timeout=3)
        try:
            await connection.execute(
                """
                CREATE TABLE users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(64) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                );
                CREATE TABLE creators (
                    id UUID PRIMARY KEY,
                    name VARCHAR(500) NOT NULL
                );
                CREATE TABLE subscriptions (
                    id UUID PRIMARY KEY,
                    creator_id UUID NOT NULL REFERENCES creators(id),
                    name VARCHAR(500),
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    sync_enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    sync_interval_hours INTEGER NOT NULL DEFAULT 6,
                    schedule_mode VARCHAR(20),
                    schedule_rule JSONB,
                    scheduled_times VARCHAR(100),
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    CONSTRAINT ck_subscriptions_schedule_mode CHECK (
                        schedule_mode IS NULL OR schedule_mode IN ('interval', 'calendar', 'manual')
                    ),
                    CONSTRAINT ck_subscriptions_schedule_sync_consistent CHECK (
                        (schedule_mode = 'manual' AND sync_enabled IS FALSE) OR
                        (schedule_mode IS DISTINCT FROM 'manual' AND sync_enabled IS TRUE)
                    )
                );
                CREATE TABLE subscription_sources (
                    id UUID PRIMARY KEY,
                    subscription_id UUID NOT NULL REFERENCES subscriptions(id),
                    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    last_successful_auth TIMESTAMPTZ,
                    auth_healthy BOOLEAN NOT NULL DEFAULT TRUE,
                    last_synced_at TIMESTAMPTZ,
                    last_attempted_at TIMESTAMPTZ,
                    next_sync_at TIMESTAMPTZ,
                    auth_status VARCHAR(30),
                    auth_error_reason TEXT,
                    last_auth_checked_at TIMESTAMPTZ,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                );
                CREATE TABLE download_jobs (id UUID PRIMARY KEY);
                CREATE TABLE task_runs (id UUID PRIMARY KEY);
                INSERT INTO users (
                    username, password_hash, is_active, is_admin, created_at
                ) VALUES (
                    'legacy-schedule-admin', 'x', TRUE, TRUE, '2026-01-01T00:00:00Z'
                );
                INSERT INTO creators (id, name) VALUES
                    ('00000000-0000-0000-0000-000000000011', 'Zero Interval'),
                    ('00000000-0000-0000-0000-000000000012', 'Null Calendar Rule');
                INSERT INTO subscriptions (
                    id, creator_id, name, sync_enabled, sync_interval_hours,
                    schedule_mode, schedule_rule, scheduled_times
                ) VALUES
                    (
                        '00000000-0000-0000-0000-000000000021',
                        '00000000-0000-0000-0000-000000000011',
                        'Zero Interval', TRUE, 0, 'interval', NULL, NULL
                    ),
                    (
                        '00000000-0000-0000-0000-000000000022',
                        '00000000-0000-0000-0000-000000000012',
                        'Null Calendar Rule', TRUE, 6, 'calendar', NULL, '03:00'
                    );
                INSERT INTO subscription_sources (
                    id, subscription_id, is_enabled, auth_healthy
                ) VALUES
                    (
                        '00000000-0000-0000-0000-000000000031',
                        '00000000-0000-0000-0000-000000000021', TRUE, TRUE
                    ),
                    (
                        '00000000-0000-0000-0000-000000000032',
                        '00000000-0000-0000-0000-000000000022', TRUE, TRUE
                    );
                """
            )
        finally:
            await connection.close()

    async def read_memberships() -> list[tuple]:
        connection = await asyncpg.connect(asyncpg_url, timeout=3)
        try:
            rows = await connection.fetch(
                """
                SELECT name, sync_enabled, sync_interval_hours, schedule_mode,
                       schedule_rule, scheduled_times
                FROM user_subscriptions
                ORDER BY name
                """
            )
            return [tuple(row) for row in rows]
        finally:
            await connection.close()

    async def drop_database() -> None:
        admin = await asyncpg.connect(test_db_base_url, timeout=3)
        try:
            await admin.execute(f'DROP DATABASE IF EXISTS "{database_name}" WITH (FORCE)')
        finally:
            await admin.close()

    try:
        asyncio.run(create_database_and_predecessor_schema())
        environment = {**os.environ, "DATABASE_URL": database_url}
        stamped = subprocess.run(
            [sys.executable, "-m", "alembic", "stamp", "b3d5f7a9c1e4"],
            cwd=backend_dir,
            env=environment,
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert stamped.returncode == 0, stamped.stderr
        upgraded = subprocess.run(
            [sys.executable, "-m", "alembic", "upgrade", "f4a6c8e0b2d4"],
            cwd=backend_dir,
            env=environment,
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert upgraded.returncode == 0, upgraded.stderr
        assert asyncio.run(read_memberships()) == [
            ("Null Calendar Rule", True, 6, "calendar", None, "03:00"),
            ("Zero Interval", True, 0, "interval", None, None),
        ]
    finally:
        asyncio.run(drop_database())


def test_private_discovery_models_register_ownership_and_source_constraints():
    """Removing user ownership or uniqueness would leak private discovery state."""
    import app.models  # noqa: F401 - registers all model tables
    from app.models import Base

    memberships = Base.metadata.tables["user_subscriptions"]
    membership_sources = Base.metadata.tables["user_subscription_sources"]
    accounts = Base.metadata.tables["remote_accounts"]
    candidates = Base.metadata.tables["discovery_candidates"]

    assert {
        "name",
        "is_active",
        "sync_enabled",
        "sync_interval_hours",
        "schedule_mode",
        "schedule_rule",
        "scheduled_times",
    }.issubset(memberships.c.keys())
    assert "is_enabled" not in memberships.c
    assert memberships.c.name.type.length == 500

    assert any(
        {"user_id", "subscription_id"} == set(constraint.columns.keys())
        for constraint in memberships.constraints
        if constraint.__class__.__name__ == "UniqueConstraint"
    )
    assert any(
        {"user_id", "source"} == set(constraint.columns.keys())
        for constraint in accounts.constraints
        if constraint.__class__.__name__ == "UniqueConstraint"
    )
    assert any(
        {"remote_account_id", "source_creator_id"} == set(constraint.columns.keys())
        for constraint in candidates.constraints
        if constraint.__class__.__name__ == "UniqueConstraint"
    )
    assert membership_sources.c.remote_account_id.nullable is True
    assert {"user_id", "subscription_id"}.issubset(membership_sources.c.keys())
    assert "user_id" in candidates.c
    composite_foreign_keys = {
        (tuple(foreign_key.parent.name for foreign_key in constraint.elements), constraint.name)
        for constraint in membership_sources.foreign_key_constraints
    }
    assert (("user_subscription_id", "user_id", "subscription_id"), "fk_user_subscription_sources_membership_owner") in composite_foreign_keys
    assert (("subscription_source_id", "subscription_id"), "fk_user_subscription_sources_source_subscription") in composite_foreign_keys
    assert (("remote_account_id", "user_id"), "fk_user_subscription_sources_remote_account_owner") in composite_foreign_keys
    candidate_foreign_keys = {
        (tuple(foreign_key.parent.name for foreign_key in constraint.elements), constraint.name)
        for constraint in candidates.foreign_key_constraints
    }
    assert (("remote_account_id", "user_id"), "fk_discovery_candidates_account_owner") in candidate_foreign_keys
    assert (("user_subscription_id", "user_id", "subscription_id"), "fk_discovery_candidates_membership_owner") in candidate_foreign_keys
    assert isinstance(accounts.c.scan_cursor.type, JSONB)
    assert isinstance(accounts.c.scopes.type, JSONB)
    assert isinstance(accounts.c.collection_selectors.type, JSONB)
    assert isinstance(candidates.c.metadata.type, JSONB)
    assert candidates.c.is_following.nullable is False
    membership_checks = {
        constraint.name
        for constraint in memberships.constraints
        if constraint.__class__.__name__ == "CheckConstraint"
    }
    assert {
        "ck_user_subscriptions_schedule_mode",
        "ck_user_subscriptions_schedule_sync_consistent",
    }.issubset(membership_checks)
    assert all(
        foreign_key.ondelete == "RESTRICT"
        for table in (memberships, membership_sources, accounts, candidates)
        for foreign_key in table.foreign_keys
    )


def test_membership_schemas_own_private_schedule_and_normalize_manual_mode():
    """Removing private schedule fields or manual consistency would restore a shared policy."""
    from app.schemas.remote_discovery import (
        UserSubscriptionCreate,
        UserSubscriptionRead,
        UserSubscriptionUpdate,
    )

    subscription_id = uuid4()
    defaults = UserSubscriptionCreate(subscription_id=subscription_id)
    assert defaults.model_dump() == {
        "subscription_id": subscription_id,
        "name": None,
        "is_active": True,
        "sync_enabled": True,
        "sync_interval_hours": 6,
        "schedule_mode": None,
        "schedule_rule": None,
        "scheduled_times": None,
    }

    manual = UserSubscriptionCreate(
        subscription_id=subscription_id,
        schedule_mode="manual",
        sync_enabled=True,
    )
    assert manual.schedule_mode == "manual"
    assert manual.sync_enabled is False

    disabled = UserSubscriptionCreate(
        subscription_id=subscription_id,
        sync_enabled=False,
    )
    assert disabled.schedule_mode == "manual"
    assert disabled.sync_enabled is False

    inherit = UserSubscriptionUpdate(
        schedule_mode="inherit",
        schedule_rule={"frequency": "daily", "times": ["03:00"]},
    )
    assert inherit.schedule_mode is None
    assert inherit.schedule_rule is None
    assert inherit.sync_enabled is True

    with pytest.raises(ValidationError):
        UserSubscriptionCreate(
            subscription_id=subscription_id,
            schedule_mode="calendar",
        )
    with pytest.raises(ValidationError):
        UserSubscriptionCreate(subscription_id=subscription_id, name="x" * 501)

    now = datetime.now(timezone.utc)
    payload = UserSubscriptionRead.model_validate({
        "id": uuid4(),
        "user_id": 7,
        "subscription_id": subscription_id,
        "name": "Private artist label",
        "is_active": True,
        "sync_enabled": True,
        "sync_interval_hours": 12,
        "schedule_mode": "interval",
        "schedule_rule": None,
        "scheduled_times": "03:00,21:00",
        "created_at": now,
        "updated_at": now,
    }).model_dump()
    assert payload["name"] == "Private artist label"
    assert payload["sync_interval_hours"] == 12
    assert "is_enabled" not in payload


def test_remote_account_input_has_safe_automatic_import_defaults_and_cap():
    """Changing opt-in/default cap could silently import an unsafe number of follows."""
    from app.schemas.remote_discovery import RemoteAccountCreate

    account = RemoteAccountCreate(source="pixiv", auth_method="refresh_token")

    assert account.auto_import_enabled is False
    assert account.auto_import_min_confidence == "high"
    assert account.auto_import_limit == 25
    assert account.auth_method == "refresh_token"
    assert account.scopes == []
    assert account.collection_selectors == []
    other = RemoteAccountCreate(source="pixiv")
    account.scopes.append("follow.read")
    account.collection_selectors.append({"restrict": "private"})
    assert other.scopes == []
    assert other.collection_selectors == []
    with pytest.raises(ValidationError):
        RemoteAccountCreate(source="pixiv", auto_import_limit=201)
    with pytest.raises(ValidationError):
        RemoteAccountCreate(source="mastodon")
    with pytest.raises(ValidationError):
        RemoteAccountCreate(source="pixiv", auth_method="cookie")
    with pytest.raises(ValidationError):
        RemoteAccountCreate(source="x", auth_method="x" * 51)


def test_remote_account_read_and_repr_never_expose_ciphertext():
    """Adding a credential field to API reads or repr would expose a durable secret."""
    from app.models import RemoteAccount
    from app.schemas.remote_discovery import RemoteAccountRead

    account = RemoteAccount(
        id=uuid4(),
        user_id=7,
        source="x",
        auth_method="oauth2",
        scopes=["users.read", "follows.read"],
        collection_selectors=[{"list_id": "123"}],
        credential_ciphertext="ciphertext-that-must-stay-private",
        is_enabled=True,
        scan_interval_hours=24,
        auto_import_enabled=False,
        auto_import_min_confidence="high",
        auto_import_limit=25,
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    )

    payload = RemoteAccountRead.model_validate(account).model_dump()

    assert "credential_ciphertext" not in payload
    assert payload["auth_method"] == "oauth2"
    assert payload["scopes"] == ["users.read", "follows.read"]
    assert payload["collection_selectors"] == [{"list_id": "123"}]
    assert "ciphertext-that-must-stay-private" not in repr(account)


def test_candidate_read_uses_canonical_identity_and_remote_follow_state():
    """Renaming the provider identity or omitting follow state would break scan upserts."""
    from app.models import DiscoveryCandidate
    from app.schemas.remote_discovery import DiscoveryCandidateRead

    now = datetime.now(timezone.utc)
    candidate = DiscoveryCandidate(
        id=uuid4(),
        remote_account_id=uuid4(),
        user_id=7,
        source_creator_id="12539859",
        display_name="Artist",
        is_following=True,
        confidence="low",
        state="pending",
        created_at=now,
        updated_at=now,
    )

    payload = DiscoveryCandidateRead.model_validate(candidate).model_dump()

    assert payload["source_creator_id"] == "12539859"
    assert payload["is_following"] is True
    assert "remote_creator_id" not in payload


def test_download_and_task_records_hold_only_optional_opaque_trigger_ids():
    """Dropping nullable trigger IDs prevents later shared download attribution."""
    from app.models import DownloadJob, TaskRun

    for model in (DownloadJob, TaskRun):
        table = model.__table__
        assert table.c.triggering_user_subscription_id.nullable is True
        assert table.c.triggering_remote_account_id.nullable is True
        assert table.c.triggering_user_subscription_id.type.python_type is type(uuid4())
        assert table.c.triggering_remote_account_id.type.python_type is type(uuid4())


def test_single_migration_creates_enforced_private_schema_before_backfill(monkeypatch):
    """A later corrective revision would leave an unsafe intermediate upgrade state."""
    versions = Path(__file__).resolve().parents[1] / "alembic" / "versions"
    migration_path = versions / "f4a6c8e0b2d4_add_private_remote_discovery_persistence.py"
    assert not (versions / "f5b7d9e1a3c5_enforce_private_discovery_ownership.py").exists()
    spec = spec_from_file_location("remote_discovery_migration", migration_path)
    assert spec and spec.loader
    migration = module_from_spec(spec)
    spec.loader.exec_module(migration)

    statements: list[str] = []
    created_tables: dict[str, tuple] = {}

    class Recorder:
        def create_table(self, *args, **kwargs):
            created_tables[args[0]] = args[1:]
            return None

        def create_index(self, *args, **kwargs):
            return None

        def create_unique_constraint(self, *args, **kwargs):
            return None

        def add_column(self, *args, **kwargs):
            return None

        def create_foreign_key(self, *args, **kwargs):
            return None

        def execute(self, statement):
            statements.append(str(statement))

    monkeypatch.setattr(migration, "op", Recorder())
    migration.upgrade()

    assert migration.down_revision == "b3d5f7a9c1e4"
    assert set(created_tables) == {
        "user_subscriptions",
        "remote_accounts",
        "user_subscription_sources",
        "discovery_candidates",
    }
    assert list(created_tables).index("user_subscriptions") < list(created_tables).index("user_subscription_sources")
    assert list(created_tables).index("remote_accounts") < list(created_tables).index("user_subscription_sources")
    assert list(created_tables).index("remote_accounts") < list(created_tables).index("discovery_candidates")

    binding_columns = {column.name for column in created_tables["user_subscription_sources"] if hasattr(column, "name")}
    membership_columns = {column.name for column in created_tables["user_subscriptions"] if hasattr(column, "name")}
    account_columns = {column.name for column in created_tables["remote_accounts"] if hasattr(column, "name")}
    candidate_columns = {column.name for column in created_tables["discovery_candidates"] if hasattr(column, "name")}
    assert {
        "name",
        "is_active",
        "sync_enabled",
        "sync_interval_hours",
        "schedule_mode",
        "schedule_rule",
        "scheduled_times",
    }.issubset(membership_columns)
    assert "is_enabled" not in membership_columns
    assert {"auth_method", "scopes", "collection_selectors"}.issubset(account_columns)
    assert {"user_id", "subscription_id"}.issubset(binding_columns)
    assert {"user_id", "source_creator_id", "is_following"}.issubset(candidate_columns)
    assert "remote_creator_id" not in candidate_columns
    binding_constraints = {
        constraint.name
        for constraint in created_tables["user_subscription_sources"]
        if getattr(constraint, "name", None)
    }
    candidate_constraints = {
        constraint.name
        for constraint in created_tables["discovery_candidates"]
        if getattr(constraint, "name", None)
    }
    assert {
        "fk_user_subscription_sources_membership_owner",
        "fk_user_subscription_sources_source_subscription",
        "fk_user_subscription_sources_remote_account_owner",
    }.issubset(binding_constraints)
    assert {
        "fk_discovery_candidates_account_owner",
        "fk_discovery_candidates_membership_owner",
        "ck_discovery_candidates_membership_subscription",
    }.issubset(candidate_constraints)

    backfills = [statement for statement in statements if "INSERT INTO user_subscriptions" in statement]
    assert len(backfills) == 1
    backfill = backfills[0]
    normalized_backfill = " ".join(backfill.split())
    assert "is_active IS TRUE" in backfill
    assert "is_admin IS TRUE" in backfill
    assert "ORDER BY created_at ASC, id ASC" in backfill
    assert "ON CONFLICT (user_id, subscription_id) DO NOTHING" in backfill
    assert (
        "name, is_active, sync_enabled, sync_interval_hours, schedule_mode, "
        "schedule_rule, scheduled_times"
    ) in normalized_backfill
    assert (
        "subscription.name, subscription.is_active, subscription.sync_enabled, "
        "subscription.sync_interval_hours, subscription.schedule_mode, "
        "subscription.schedule_rule, subscription.scheduled_times"
    ) in normalized_backfill
    source_backfills = [statement for statement in statements if "INSERT INTO user_subscription_sources" in statement]
    assert len(source_backfills) == 1
    assert "user_id, subscription_id" in source_backfills[0]
    assert "membership.user_id, membership.subscription_id" in source_backfills[0]
    assert "credential_ciphertext" not in backfill


async def _private_binding_fixture(db, suffix: str):
    from app.models import (
        Creator,
        RemoteAccount,
        Subscription,
        SubscriptionSource,
        User,
        UserSubscription,
    )

    first_user = User(username=f"remote-owner-a-{suffix}", password_hash="x", is_active=True)
    second_user = User(username=f"remote-owner-b-{suffix}", password_hash="x", is_active=True)
    first_creator = Creator(name=f"remote-owner-creator-a-{suffix}")
    second_creator = Creator(name=f"remote-owner-creator-b-{suffix}")
    db.add_all([first_user, second_user, first_creator, second_creator])
    await db.flush()
    first_subscription = Subscription(creator_id=first_creator.id, name=f"remote-owner-sub-a-{suffix}")
    second_subscription = Subscription(creator_id=second_creator.id, name=f"remote-owner-sub-b-{suffix}")
    db.add_all([first_subscription, second_subscription])
    await db.flush()
    first_source = SubscriptionSource(
        subscription_id=first_subscription.id,
        source="pixiv",
        source_url=f"https://example.test/{suffix}/a",
    )
    second_source = SubscriptionSource(
        subscription_id=second_subscription.id,
        source="pixiv",
        source_url=f"https://example.test/{suffix}/b",
    )
    first_membership = UserSubscription(user_id=first_user.id, subscription_id=first_subscription.id)
    second_membership = UserSubscription(user_id=second_user.id, subscription_id=first_subscription.id)
    second_account = RemoteAccount(user_id=second_user.id, source="pixiv")
    first_account = RemoteAccount(user_id=first_user.id, source="x")
    db.add_all([
        first_source,
        second_source,
        first_membership,
        second_membership,
        second_account,
        first_account,
    ])
    await db.flush()
    return {
        "first_user": first_user,
        "second_user": second_user,
        "first_subscription": first_subscription,
        "second_subscription": second_subscription,
        "first_source": first_source,
        "second_source": second_source,
        "first_membership": first_membership,
        "second_membership": second_membership,
        "first_account": first_account,
        "second_account": second_account,
    }


@pytest.mark.integration
@pytest.mark.asyncio
async def test_database_rejects_membership_source_using_another_users_account():
    """Removing composite account ownership would let one member select another user's credential."""
    from app.database import async_session, engine
    from app.models import UserSubscriptionSource

    try:
        async with async_session() as db:
            fixture = await _private_binding_fixture(db, "cross-account")
            binding = UserSubscriptionSource(
                user_subscription_id=fixture["first_membership"].id,
                subscription_source_id=fixture["first_source"].id,
                remote_account_id=fixture["second_account"].id,
            )
            binding.user_id = fixture["first_user"].id
            binding.subscription_id = fixture["first_subscription"].id
            db.add(binding)
            with pytest.raises(IntegrityError):
                await db.commit()
    finally:
        await engine.dispose()


@pytest.mark.integration
@pytest.mark.asyncio
async def test_database_rejects_candidate_using_another_users_imported_membership():
    """Removing candidate account/membership ownership would cross-link private discovery state."""
    from app.database import async_session, engine
    from app.models import DiscoveryCandidate

    try:
        async with async_session() as db:
            fixture = await _private_binding_fixture(db, "cross-candidate")
            candidate = DiscoveryCandidate(
                remote_account_id=fixture["first_account"].id,
                source_creator_id="creator-cross-owner",
                subscription_id=fixture["first_subscription"].id,
                user_subscription_id=fixture["second_membership"].id,
            )
            candidate.user_id = fixture["first_user"].id
            db.add(candidate)
            with pytest.raises(IntegrityError):
                await db.commit()
    finally:
        await engine.dispose()


@pytest.mark.integration
@pytest.mark.asyncio
async def test_database_enforces_membership_schedule_and_candidate_defaults():
    """Losing database defaults or consistency checks would corrupt private due state."""
    from app.database import async_session, engine
    from app.models import DiscoveryCandidate, UserSubscription

    try:
        async with async_session() as db:
            fixture = await _private_binding_fixture(db, "private-defaults")
            membership = fixture["first_membership"]
            candidate = DiscoveryCandidate(
                remote_account_id=fixture["first_account"].id,
                user_id=fixture["first_user"].id,
                source_creator_id="private-default-creator",
            )
            db.add(candidate)
            await db.flush()
            await db.refresh(membership)
            await db.refresh(candidate)

            assert membership.name is None
            assert membership.is_active is True
            assert membership.sync_enabled is True
            assert membership.sync_interval_hours == 6
            assert membership.schedule_mode is None
            assert membership.schedule_rule is None
            assert membership.scheduled_times is None
            assert candidate.is_following is True

        async with async_session() as db:
            fixture = await _private_binding_fixture(db, "invalid-manual")
            invalid = UserSubscription(
                user_id=fixture["first_user"].id,
                subscription_id=fixture["second_subscription"].id,
                schedule_mode="manual",
                sync_enabled=True,
            )
            db.add(invalid)
            with pytest.raises(IntegrityError):
                await db.commit()
    finally:
        await engine.dispose()


@pytest.mark.integration
@pytest.mark.asyncio
async def test_database_rejects_membership_source_from_another_canonical_subscription():
    """Removing the composite canonical FK would corrupt a membership's due/auth policy."""
    from app.database import async_session, engine
    from app.models import UserSubscriptionSource

    try:
        async with async_session() as db:
            fixture = await _private_binding_fixture(db, "cross-subscription")
            binding = UserSubscriptionSource(
                user_subscription_id=fixture["first_membership"].id,
                subscription_source_id=fixture["second_source"].id,
            )
            binding.user_id = fixture["first_user"].id
            binding.subscription_id = fixture["first_subscription"].id
            db.add(binding)
            with pytest.raises(IntegrityError):
                await db.commit()
    finally:
        await engine.dispose()
