"""make_source_creator_creator_id_nullable

Revision ID: 49d9c60be03c
Revises: 1e01b83a614f
Create Date: 2026-05-15 07:00:07.003849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49d9c60be03c'
down_revision: Union[str, None] = '1e01b83a614f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_creators', 'creator_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_creators', 'creator_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
