"""add_naming_templates_table

Revision ID: 54fe9ca906e2
Revises: 7213b2b34d8a
Create Date: 2026-05-16 12:41:19.045112
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '54fe9ca906e2'
down_revision: Union[str, None] = '7213b2b34d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
