"""add_subscription_sync_interval

Revision ID: ea15eaa99d22
Revises: 49d9c60be03c
Create Date: 2026-05-16 06:33:39.072730
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea15eaa99d22'
down_revision: Union[str, None] = '49d9c60be03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
